/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class w_Global */

#ifndef _Included_w_Global
#define _Included_w_Global
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     w_Global
 * Method:    getInstances
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_w_Global_getInstances
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
